//! Rendering the generated Buck2 files.
//!
//! Every renderer here returns a `String` and touches no filesystem, so
//! `buckify --check` compares in memory against what is on disk while sharing
//! all rendering with the write path. The two cannot drift.

pub mod bzl;
pub mod config;
pub mod emit;
pub mod format;

use std::collections::BTreeMap;
use std::path::{Component, Path, PathBuf};

use crate::config::Platform;
use crate::error::BuckError;
use crate::packages::Entry;

/// The banner every generated file opens with (spec §3).
///
/// Four lines and a trailing newline. `##` rather than `#` so it reads as a
/// block in Starlark, matching design §7 and §8.
pub const HEADER: &str = "\
##
## @generated by pudu
## Do not edit by hand.
##
";

/// The three generated files, rendered but not yet written.
#[derive(Debug, PartialEq, Eq)]
pub struct Generated {
    pub buck: String,
    pub bzl: String,
    pub config: String,
}

impl Generated {
    /// Each file paired with its path under `third_party_dir`.
    fn files<'a>(&'a self, third_party_dir: &Path) -> [(PathBuf, &'a str); 3] {
        [
            (third_party_dir.join("BUCK"), self.buck.as_str()),
            (third_party_dir.join("pudu.bzl"), self.bzl.as_str()),
            (
                third_party_dir.join("config").join("BUCK"),
                self.config.as_str(),
            ),
        ]
    }

    /// Write all three files, or none of them.
    ///
    /// Each file is written to a fresh temp file in its own target
    /// directory and only then renamed into place — `fs::rename` within a
    /// directory is atomic on both Linux and macOS. Every temp file is
    /// created before any rename is attempted, so a failure creating or
    /// writing one (a read-only directory, a full disk, …) leaves every
    /// target path exactly as it was; nothing has been renamed yet. The
    /// remaining risk — a rename itself failing after an earlier one in the
    /// same call already succeeded — is possible in principle (e.g. the
    /// directory disappearing between the temp-file check and the rename)
    /// but not from any permission on the target file itself, since rename
    /// does not open or truncate it.
    pub fn write(&self, third_party_dir: &Path) -> Result<(), BuckError> {
        let config_dir = third_party_dir.join("config");
        std::fs::create_dir_all(&config_dir).map_err(|source| BuckError::WriteFailed {
            path: config_dir,
            source,
        })?;

        let mut pending = Vec::with_capacity(3);
        for (path, contents) in self.files(third_party_dir) {
            let dir = path
                .parent()
                .expect("files() always returns a path with a parent");
            let mut tmp =
                tempfile::NamedTempFile::new_in(dir).map_err(|source| BuckError::WriteFailed {
                    path: path.clone(),
                    source,
                })?;
            std::io::Write::write_all(&mut tmp, contents.as_bytes()).map_err(|source| {
                BuckError::WriteFailed {
                    path: path.clone(),
                    source,
                }
            })?;
            pending.push((tmp, path));
        }
        for (tmp, path) in pending {
            tmp.persist(&path).map_err(|e| BuckError::WriteFailed {
                path,
                source: e.error,
            })?;
        }
        Ok(())
    }

    /// The first file whose contents differ from what is on disk.
    ///
    /// A missing file counts as differing, which is what makes `--check` in a
    /// tree that has never been buckified fail rather than pass vacuously.
    /// Any other read failure (permission denied, and so on) is a distinct
    /// error naming the path, rather than being folded into "differs" —
    /// "run `pudu buckify`" cannot fix an unreadable file.
    pub fn check(&self, third_party_dir: &Path) -> Result<(), BuckError> {
        for (path, contents) in self.files(third_party_dir) {
            let on_disk = match std::fs::read_to_string(&path) {
                Ok(s) => s,
                Err(source) if source.kind() == std::io::ErrorKind::NotFound => String::new(),
                Err(source) => return Err(BuckError::ReadFailed { path, source }),
            };
            if on_disk != contents {
                return Err(BuckError::Stale { path });
            }
        }
        Ok(())
    }
}

/// Render all three files. Pure — no filesystem, no network.
///
/// `third_party_dir` here is the label path — cell-relative, exactly as
/// written in `pudu.toml` — not the absolute, cwd-joined path used to read
/// and write files. A Buck label is a normalized path relative to the cell
/// root, so any `third_party_dir` that is not one (absolute, or containing
/// `.`, `..`, or an empty component) is rejected here rather than emitting a
/// label buck2 cannot parse.
pub fn generate(
    entries: &BTreeMap<String, Entry>,
    platforms: &BTreeMap<String, Platform>,
    third_party_dir: &Path,
) -> Result<Generated, BuckError> {
    let label =
        normalized_label(third_party_dir).map_err(|reason| BuckError::UnusableThirdPartyDir {
            path: third_party_dir.to_path_buf(),
            reason,
        })?;
    Ok(Generated {
        buck: emit::render(entries, &label)?,
        bzl: bzl::render(),
        config: config::render(platforms),
    })
}

/// `third_party_dir` as a Buck label path, or the reason it cannot be one.
///
/// A Buck label is a normalized path relative to the cell root: not
/// absolute, non-empty, and with every component an ordinary name — no `.`,
/// no `..`, and no empty component (what a leading, trailing or doubled `/`
/// produces). `is_absolute()` alone catches only one of these; the others
/// still produce a path buck2's parser rejects (`./third-party/js`,
/// `third-party/js/`, `../shared/tp`), just later and with a worse error.
fn normalized_label(path: &Path) -> Result<String, String> {
    if path.as_os_str().is_empty() {
        return Err("is empty".to_string());
    }
    if path.is_absolute() {
        return Err("is an absolute path".to_string());
    }

    let mut parts = Vec::new();
    for component in path.components() {
        match component {
            Component::Normal(part) => parts.push(part.to_string_lossy().into_owned()),
            Component::CurDir => return Err("contains a `.` component".to_string()),
            Component::ParentDir => return Err("contains a `..` component".to_string()),
            Component::RootDir | Component::Prefix(_) => {
                return Err("is an absolute path".to_string());
            }
        }
    }
    if parts.is_empty() {
        return Err("is empty".to_string());
    }

    // Buck labels are slash-separated regardless of host separator.
    let normalized = parts.join("/");
    let raw = path.to_string_lossy().replace('\\', "/");
    if raw != normalized {
        return Err("is not a normalized path (a leading, trailing or doubled `/`)".to_string());
    }
    Ok(normalized)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generated() -> Generated {
        Generated {
            buck: "buck-1".to_string(),
            bzl: "bzl-1".to_string(),
            config: "config-1".to_string(),
        }
    }

    fn generated_v2() -> Generated {
        Generated {
            buck: "buck-2".to_string(),
            bzl: "bzl-2".to_string(),
            config: "config-2".to_string(),
        }
    }

    // --- normalized_label ---------------------------------------------

    #[test]
    fn an_ordinary_relative_path_is_accepted() {
        assert_eq!(
            normalized_label(Path::new("third-party/js")).unwrap(),
            "third-party/js"
        );
    }

    #[test]
    fn an_absolute_path_is_rejected() {
        assert!(normalized_label(Path::new("/third-party/js")).is_err());
    }

    #[test]
    fn a_dot_prefixed_path_is_rejected() {
        assert!(normalized_label(Path::new("./third-party/js")).is_err());
    }

    #[test]
    fn a_trailing_slash_is_rejected() {
        assert!(normalized_label(Path::new("third-party/js/")).is_err());
    }

    #[test]
    fn a_dot_dot_component_is_rejected() {
        assert!(normalized_label(Path::new("../shared/tp")).is_err());
    }

    #[test]
    fn an_empty_path_is_rejected() {
        assert!(normalized_label(Path::new("")).is_err());
    }

    // --- write: atomicity ------------------------------------------------

    #[cfg(unix)]
    #[test]
    fn a_write_failure_leaves_every_file_at_its_previous_contents() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().unwrap();
        let tp = dir.path().join("third-party/js");

        generated().write(&tp).unwrap();
        let before: Vec<String> = ["BUCK", "pudu.bzl", "config/BUCK"]
            .iter()
            .map(|n| std::fs::read_to_string(tp.join(n)).unwrap())
            .collect();

        // Strip write permission from `config/`, so creating a temp file
        // there (the last of the three) fails before any rename happens.
        let config_dir = tp.join("config");
        let mut perms = std::fs::metadata(&config_dir).unwrap().permissions();
        perms.set_mode(0o555);
        std::fs::set_permissions(&config_dir, perms.clone()).unwrap();

        let result = generated_v2().write(&tp);

        // Restore permissions so the tempdir can be cleaned up.
        perms.set_mode(0o755);
        std::fs::set_permissions(&config_dir, perms).unwrap();

        assert!(
            matches!(result, Err(BuckError::WriteFailed { .. })),
            "{result:?}"
        );
        let after: Vec<String> = ["BUCK", "pudu.bzl", "config/BUCK"]
            .iter()
            .map(|n| std::fs::read_to_string(tp.join(n)).unwrap())
            .collect();
        assert_eq!(before, after, "a failed write must not touch any file");
    }

    // --- check: read failures ------------------------------------------

    #[cfg(unix)]
    #[test]
    fn an_unreadable_file_is_a_read_failure_not_stale() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().unwrap();
        let tp = dir.path().join("third-party/js");
        generated().write(&tp).unwrap();

        let buck_path = tp.join("BUCK");
        let mut perms = std::fs::metadata(&buck_path).unwrap().permissions();
        perms.set_mode(0o000);
        std::fs::set_permissions(&buck_path, perms.clone()).unwrap();

        let result = generated().check(&tp);

        perms.set_mode(0o644);
        std::fs::set_permissions(&buck_path, perms).unwrap();

        // Root ignores file permission bits, so skip the assertion when
        // running as root (as CI containers sometimes do).
        if !nix_like_root() {
            assert!(
                matches!(result, Err(BuckError::ReadFailed { .. })),
                "{result:?}"
            );
        }
    }

    #[cfg(unix)]
    fn nix_like_root() -> bool {
        // No libc dependency in this crate: shell out to `id -u` rather than
        // an FFI declaration for one call in one test.
        std::process::Command::new("id")
            .arg("-u")
            .output()
            .map(|o| String::from_utf8_lossy(&o.stdout).trim() == "0")
            .unwrap_or(false)
    }

    #[test]
    fn a_missing_file_is_stale_not_a_read_failure() {
        let dir = tempfile::tempdir().unwrap();
        let tp = dir.path().join("third-party/js");
        let result = generated().check(&tp);
        assert!(matches!(result, Err(BuckError::Stale { .. })), "{result:?}");
    }
}
