//! Rendering the generated Buck2 files.
//!
//! Every renderer here returns a `String` and touches no filesystem, so
//! `buckify --check` compares in memory against what is on disk while sharing
//! all rendering with the write path. The two cannot drift.

pub mod bzl;
pub mod config;
pub mod emit;
pub mod format;

/// The banner every generated file opens with (spec §3).
///
/// Four lines and a trailing newline. `##` rather than `#` so it reads as a
/// block in Starlark, matching design §7 and §8.
pub const HEADER: &str = "\
##
## @generated by pudu
## Do not edit by hand.
##
";
