//! The `packages.toml` package table: what `pudu vendor` records and `--check` compares.
//!
//! Keyed on `name@version` rather than the snapshot key, because a tarball has
//! no peer dependencies — one entry serves every peer instance of a package.
//!
//! Rendering is by hand. Byte-identical output across runs is an exit
//! criterion, and writing the format out makes it the spec rather than a
//! property of a serializer's table-inlining heuristics.

use std::collections::BTreeMap;
use std::fmt;
use std::path::Path;

use serde::Deserialize;

use crate::error::VendorError;

/// The package table's format version.
///
/// Reset to 1 in S3.5 when the file moved from `pudu.lock` to
/// `packages.toml`. Because the name changed in the same stage, no file any
/// earlier pudu wrote can ever be opened as a `packages.toml`, so the
/// sequence starts fresh with the new format identity rather than carrying
/// over a number that would imply a `version = 1` `packages.toml` that never
/// existed. `an_old_pudu_lock_is_not_read_as_a_package_table` pins the
/// premise.
pub const TABLE_VERSION: u32 = 1;

const HEADER: &str = "# @generated by pudu. Do not edit by hand.\n";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Entry {
    pub url: String,
    /// The lockfile's integrity string verbatim, `sha512-` prefix included.
    pub sha512: String,
    /// Lowercase hex — what `http_archive` expects.
    pub sha256: String,
    /// Compressed bytes.
    pub size: u64,
    /// The archive's single root directory, no trailing slash — what a build
    /// rule passes to `http_archive(strip_prefix = …)`.
    ///
    /// Required, because every valid archive has exactly one. Usually
    /// `package`, but `@types/*` tarballs nest under their own display name
    /// (`estree`, `node v22.20`), so it cannot be assumed. Recording it is
    /// what keeps a later build-rule pass offline: the sidecar is its only
    /// input, and re-deriving the root would mean re-downloading every
    /// tarball.
    pub root: String,
    pub bin: BTreeMap<String, String>,
    pub has_install_script: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct PackageTable {
    pub entries: BTreeMap<String, Entry>,
}

impl PackageTable {
    pub fn render(&self) -> String {
        let mut out = String::from(HEADER);
        out.push_str(&format!("version = {TABLE_VERSION}\n"));
        for (key, e) in &self.entries {
            out.push('\n');
            out.push_str(&format!("[{}]\n", quote(key)));
            out.push_str(&format!("url = {}\n", quote(&e.url)));
            out.push_str(&format!("sha512 = {}\n", quote(&e.sha512)));
            out.push_str(&format!("sha256 = {}\n", quote(&e.sha256)));
            out.push_str(&format!("size = {}\n", e.size));
            out.push_str(&format!("root = {}\n", quote(&e.root)));
            if !e.bin.is_empty() {
                let pairs: Vec<String> = e
                    .bin
                    .iter()
                    .map(|(n, p)| format!("{} = {}", bare_key(n), quote(p)))
                    .collect();
                out.push_str(&format!("bin = {{ {} }}\n", pairs.join(", ")));
            }
            if e.has_install_script {
                out.push_str("has_install_script = true\n");
            }
        }
        out
    }
}

/// A TOML bare key when `s` qualifies (ASCII letters, digits, `-`, `_`), a
/// quoted string otherwise. `bin` entry names are ordinary identifiers in
/// practice, so this keeps `bin = { a = "a.js" }` free of needless quoting.
fn bare_key(s: &str) -> String {
    let is_bare = !s.is_empty()
        && s.bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_');
    if is_bare { s.to_string() } else { quote(s) }
}

/// A TOML basic string. Keys are quoted too: `@scope/name@1.0.0` is not a
/// bare key.
fn quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 || c as u32 == 0x7F => {
                out.push_str(&format!("\\u{:04X}", c as u32))
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// What reading `packages.toml` found.
///
/// A version pudu cannot read is not an error: `--check` reports it as one
/// difference, and `vendor` rebuilds from scratch.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Loaded {
    Absent,
    WrongVersion(u32),
    Present(PackageTable),
}

#[derive(Deserialize)]
struct VersionProbe {
    version: u32,
}

#[derive(Deserialize)]
struct RawTable {
    #[serde(rename = "version")]
    _version: u32,
    #[serde(flatten)]
    entries: BTreeMap<String, RawEntry>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawEntry {
    url: String,
    sha512: String,
    sha256: String,
    size: u64,
    root: String,
    #[serde(default)]
    bin: BTreeMap<String, String>,
    #[serde(default)]
    has_install_script: bool,
}

pub fn load(path: &Path) -> Result<Loaded, VendorError> {
    let text = match std::fs::read_to_string(path) {
        Ok(t) => t,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Loaded::Absent),
        Err(e) => {
            return Err(VendorError::TableMalformed {
                path: path.to_path_buf(),
                reason: e.to_string(),
            });
        }
    };

    let malformed = |e: toml::de::Error| VendorError::TableMalformed {
        path: path.to_path_buf(),
        reason: e.to_string(),
    };

    // The version is read first and on its own, so a future format whose
    // entries do not fit `RawEntry` reports "wrong version" rather than a
    // parse error blaming the user for a file pudu generated.
    let probe: VersionProbe = toml::from_str(&text).map_err(malformed)?;
    if probe.version != TABLE_VERSION {
        return Ok(Loaded::WrongVersion(probe.version));
    }

    let raw: RawTable = toml::from_str(&text).map_err(malformed)?;
    Ok(Loaded::Present(PackageTable {
        entries: raw
            .entries
            .into_iter()
            .map(|(k, e)| {
                (
                    k,
                    Entry {
                        url: e.url,
                        sha512: e.sha512,
                        sha256: e.sha256,
                        size: e.size,
                        root: e.root,
                        bin: e.bin,
                        has_install_script: e.has_install_script,
                    },
                )
            })
            .collect(),
    }))
}

/// What `vendor` expects a table entry to say, computed offline.
///
/// Deliberately only the two fields the lockfile and `pudu.toml` can answer
/// without touching a tarball. `root`, `sha256`, `size`, and `bin` are all
/// properties of the bytes, so `--check` cannot form an expectation for them
/// and there is no `RootChanged` difference: a root that changed did so
/// because the tarball did, which the `sha512` already catches.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Expected {
    pub url: String,
    pub sha512: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Difference {
    Missing(String),
    Extra(String),
    UrlChanged {
        key: String,
        was: String,
        now: String,
    },
    Sha512Changed {
        key: String,
        was: String,
        now: String,
    },
    UnsupportedVersion {
        found: u32,
    },
}

impl fmt::Display for Difference {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Difference::Missing(key) => write!(f, "packages.toml has no entry for `{key}`"),
            Difference::Extra(key) => {
                write!(
                    f,
                    "packages.toml has an entry for `{key}`, which is no longer needed"
                )
            }
            Difference::UrlChanged { key, was, now } => {
                write!(f, "`{key}`: url is `{was}`, expected `{now}`")
            }
            Difference::Sha512Changed { key, was, now } => {
                write!(f, "`{key}`: sha512 is `{was}`, expected `{now}`")
            }
            Difference::UnsupportedVersion { found } => write!(
                f,
                "packages.toml says version {found}; this pudu writes version {TABLE_VERSION}"
            ),
        }
    }
}

/// Compare what the lockfile and config imply against what is on disk.
///
/// Offline by construction: nothing here reads a tarball. That is the whole
/// point of `--check` as a CI gate.
pub fn staleness(expected: &BTreeMap<String, Expected>, loaded: &Loaded) -> Vec<Difference> {
    let empty = BTreeMap::new();
    let found = match loaded {
        // One problem, not one per package.
        Loaded::WrongVersion(found) => {
            return vec![Difference::UnsupportedVersion { found: *found }];
        }
        Loaded::Absent => &empty,
        Loaded::Present(s) => &s.entries,
    };

    let mut out = Vec::new();
    for (key, want) in expected {
        match found.get(key) {
            None => out.push(Difference::Missing(key.clone())),
            Some(have) => {
                if have.url != want.url {
                    out.push(Difference::UrlChanged {
                        key: key.clone(),
                        was: have.url.clone(),
                        now: want.url.clone(),
                    });
                }
                if have.sha512 != want.sha512 {
                    out.push(Difference::Sha512Changed {
                        key: key.clone(),
                        was: have.sha512.clone(),
                        now: want.sha512.clone(),
                    });
                }
            }
        }
    }
    for key in found.keys() {
        if !expected.contains_key(key) {
            out.push(Difference::Extra(key.clone()));
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(url: &str) -> Entry {
        Entry {
            url: url.to_string(),
            sha512: "sha512-AAAA".to_string(),
            sha256: "ff00".to_string(),
            size: 42,
            root: "package".to_string(),
            bin: BTreeMap::new(),
            has_install_script: false,
        }
    }

    fn sidecar(pairs: &[(&str, Entry)]) -> PackageTable {
        PackageTable {
            entries: pairs
                .iter()
                .map(|(k, v)| (k.to_string(), v.clone()))
                .collect(),
        }
    }

    #[test]
    fn rendering_is_stable_and_sorted_regardless_of_insertion_order() {
        let a = sidecar(&[("b@1.0.0", entry("u2")), ("a@1.0.0", entry("u1"))]);
        let b = sidecar(&[("a@1.0.0", entry("u1")), ("b@1.0.0", entry("u2"))]);
        assert_eq!(a.render(), b.render());
        let text = a.render();
        assert!(
            text.find("[\"a@1.0.0\"]").unwrap() < text.find("[\"b@1.0.0\"]").unwrap(),
            "entries must be sorted:\n{text}"
        );
    }

    #[test]
    fn the_generated_header_and_version_lead_the_file() {
        let text = sidecar(&[("a@1.0.0", entry("u"))]).render();
        assert!(
            text.starts_with("# @generated by pudu. Do not edit by hand.\nversion = 1\n"),
            "{text}"
        );
    }

    #[test]
    fn an_empty_bin_and_a_false_flag_are_omitted() {
        let text = sidecar(&[("a@1.0.0", entry("u"))]).render();
        assert!(!text.contains("bin ="), "{text}");
        assert!(!text.contains("has_install_script"), "{text}");
    }

    #[test]
    fn a_bin_map_and_a_true_flag_are_rendered_inline() {
        let mut e = entry("u");
        e.bin = BTreeMap::from([
            ("z".to_string(), "z.js".to_string()),
            ("a".to_string(), "a.js".to_string()),
        ]);
        e.has_install_script = true;
        let text = sidecar(&[("a@1.0.0", e)]).render();
        assert!(
            text.contains(r#"bin = { a = "a.js", z = "z.js" }"#),
            "{text}"
        );
        assert!(text.contains("has_install_script = true"), "{text}");
    }

    #[test]
    fn bin_names_that_are_not_bare_toml_keys_are_quoted() {
        let mut e = entry("u");
        e.bin = BTreeMap::from([
            ("tool".to_string(), "tool.js".to_string()),
            ("foo.js".to_string(), "foo.js".to_string()),
            ("$".to_string(), "dollar.js".to_string()),
            ("it's".to_string(), "its.js".to_string()),
            (String::new(), "empty.js".to_string()),
        ]);
        let original = sidecar(&[("a@1.0.0", e)]);
        let text = original.render();

        assert!(text.contains("tool = \"tool.js\""), "{text}");
        assert!(text.contains("\"foo.js\" = \"foo.js\""), "{text}");
        assert!(text.contains("\"$\" = \"dollar.js\""), "{text}");
        assert!(text.contains("\"it's\" = \"its.js\""), "{text}");
        assert!(text.contains("\"\" = \"empty.js\""), "{text}");

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pudu.lock");
        std::fs::write(&path, &text).unwrap();
        let Loaded::Present(parsed) = load(&path).unwrap() else {
            panic!("expected a parsed sidecar");
        };
        assert_eq!(parsed, original);
    }

    #[test]
    fn render_then_load_round_trips() {
        let mut e = entry("https://example.com/a.tgz");
        e.bin = BTreeMap::from([("a".to_string(), "bin/a.js".to_string())]);
        e.has_install_script = true;
        let original = sidecar(&[("@scope/a@1.0.0", e), ("b@2.0.0", entry("u2"))]);

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pudu.lock");
        std::fs::write(&path, original.render()).unwrap();

        let Loaded::Present(parsed) = load(&path).unwrap() else {
            panic!("expected a parsed sidecar");
        };
        assert_eq!(parsed, original);
        assert_eq!(parsed.render(), original.render());
    }

    #[test]
    fn a_root_that_is_not_package_round_trips_through_render_and_load() {
        // `@types/node@22.20.x` really does unpack to `node v22.20/` — a
        // root that is neither `package` nor a bare TOML key, so this also
        // exercises the quoting rules on a value with a space in it.
        let mut e = entry("https://registry.npmjs.org/@types/node/-/node-22.20.0.tgz");
        e.root = "node v22.20".to_string();
        let original = sidecar(&[("@types/node@22.20.0", e)]);
        let text = original.render();
        assert!(
            text.contains(r#"root = "node v22.20""#),
            "the archive's real root must be recorded verbatim:\n{text}"
        );

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pudu.lock");
        std::fs::write(&path, &text).unwrap();
        let Loaded::Present(parsed) = load(&path).unwrap() else {
            panic!("expected a parsed sidecar");
        };
        assert_eq!(parsed, original);
        assert_eq!(parsed.entries["@types/node@22.20.0"].root, "node v22.20");
    }

    #[test]
    fn an_entry_with_no_root_is_an_error() {
        // `root` is required, not defaulted: an entry that omits it would
        // otherwise silently read back as an empty strip_prefix.
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pudu.lock");
        std::fs::write(
            &path,
            "version = 1\n\n[\"a@1.0.0\"]\nurl = \"u\"\nsha512 = \"sha512-AAAA\"\nsha256 = \"ff00\"\nsize = 42\n",
        )
        .unwrap();
        assert!(matches!(
            load(&path).unwrap_err(),
            VendorError::TableMalformed { .. }
        ));
    }

    #[test]
    fn a_missing_file_loads_as_absent() {
        let dir = tempfile::tempdir().unwrap();
        assert!(matches!(
            load(&dir.path().join("nope.lock")).unwrap(),
            Loaded::Absent
        ));
    }

    #[test]
    fn a_future_version_loads_as_wrong_version_not_an_error() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pudu.lock");
        std::fs::write(&path, "version = 7\n").unwrap();
        assert!(matches!(load(&path).unwrap(), Loaded::WrongVersion(7)));
    }

    #[test]
    fn unparseable_toml_is_an_error_naming_the_path() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pudu.lock");
        std::fs::write(&path, "this is not toml [[[").unwrap();
        let err = load(&path).unwrap_err();
        let VendorError::TableMalformed { path: p, .. } = &err else {
            panic!("wrong variant: {err:?}");
        };
        assert_eq!(p, &path);
    }

    #[test]
    fn an_entry_missing_a_required_field_is_an_error() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pudu.lock");
        std::fs::write(&path, "version = 1\n\n[\"a@1.0.0\"]\nurl = \"u\"\n").unwrap();
        assert!(matches!(
            load(&path).unwrap_err(),
            VendorError::TableMalformed { .. }
        ));
    }

    #[test]
    fn an_entry_with_an_unknown_field_is_an_error() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pudu.lock");
        std::fs::write(
            &path,
            "version = 1\n\n[\"a@1.0.0\"]\nurl = \"u\"\nsha512 = \"sha512-AAAA\"\nsha256 = \"ff00\"\nsize = 42\nroot = \"package\"\nmystery = \"x\"\n",
        )
        .unwrap();
        assert!(matches!(
            load(&path).unwrap_err(),
            VendorError::TableMalformed { .. }
        ));
    }

    // --- staleness --------------------------------------------------------

    fn expected(pairs: &[(&str, &str, &str)]) -> BTreeMap<String, Expected> {
        pairs
            .iter()
            .map(|(k, url, sha)| {
                (
                    k.to_string(),
                    Expected {
                        url: url.to_string(),
                        sha512: sha.to_string(),
                    },
                )
            })
            .collect()
    }

    #[test]
    fn a_matching_sidecar_is_not_stale() {
        let e = expected(&[("a@1.0.0", "u1", "sha512-AAAA")]);
        let s = Loaded::Present(sidecar(&[("a@1.0.0", entry("u1"))]));
        assert_eq!(staleness(&e, &s), vec![]);
    }

    #[test]
    fn a_package_with_no_entry_is_missing() {
        let e = expected(&[("a@1.0.0", "u1", "sha512-AAAA")]);
        let s = Loaded::Present(PackageTable::default());
        assert_eq!(
            staleness(&e, &s),
            vec![Difference::Missing("a@1.0.0".to_string())]
        );
    }

    #[test]
    fn an_entry_for_a_package_no_longer_in_the_graph_is_extra() {
        let e = expected(&[]);
        let s = Loaded::Present(sidecar(&[("gone@1.0.0", entry("u"))]));
        assert_eq!(
            staleness(&e, &s),
            vec![Difference::Extra("gone@1.0.0".to_string())]
        );
    }

    #[test]
    fn a_changed_url_is_reported_with_both_values() {
        let e = expected(&[("a@1.0.0", "u2", "sha512-AAAA")]);
        let s = Loaded::Present(sidecar(&[("a@1.0.0", entry("u1"))]));
        assert_eq!(
            staleness(&e, &s),
            vec![Difference::UrlChanged {
                key: "a@1.0.0".to_string(),
                was: "u1".to_string(),
                now: "u2".to_string(),
            }]
        );
    }

    #[test]
    fn a_republished_version_is_caught_by_the_sha512() {
        let e = expected(&[("a@1.0.0", "u1", "sha512-BBBB")]);
        let s = Loaded::Present(sidecar(&[("a@1.0.0", entry("u1"))]));
        assert_eq!(
            staleness(&e, &s),
            vec![Difference::Sha512Changed {
                key: "a@1.0.0".to_string(),
                was: "sha512-AAAA".to_string(),
                now: "sha512-BBBB".to_string(),
            }]
        );
    }

    #[test]
    fn an_absent_sidecar_reports_every_package_as_missing() {
        let e = expected(&[("a@1.0.0", "u1", "s"), ("b@1.0.0", "u2", "s")]);
        assert_eq!(staleness(&e, &Loaded::Absent).len(), 2);
    }

    #[test]
    fn a_wrong_version_is_a_single_difference_not_a_flood() {
        let e = expected(&[("a@1.0.0", "u1", "s"), ("b@1.0.0", "u2", "s")]);
        assert_eq!(
            staleness(&e, &Loaded::WrongVersion(7)),
            vec![Difference::UnsupportedVersion { found: 7 }],
            "a sidecar pudu cannot read is one problem, not one per package"
        );
    }

    #[test]
    fn every_difference_renders_a_message_naming_its_subject() {
        let cases = [
            (Difference::Missing("a@1".into()), "a@1"),
            (Difference::Extra("b@2".into()), "b@2"),
            (
                Difference::UrlChanged {
                    key: "c@3".into(),
                    was: "old".into(),
                    now: "new".into(),
                },
                "c@3",
            ),
            (
                Difference::Sha512Changed {
                    key: "d@4".into(),
                    was: "old".into(),
                    now: "new".into(),
                },
                "d@4",
            ),
            (Difference::UnsupportedVersion { found: 7 }, "7"),
        ];
        for (d, needle) in cases {
            let s = d.to_string();
            assert!(s.contains(needle), "{s:?} must contain {needle:?}");
        }
    }
}
